version: '3'
services:
  app:
    build: ./
    command: sh -c "flask run --host=0.0.0.0 --port=5000"
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server.py
    working_dir: /code/
    volumes:
      - ./:/code/:cached