version: '3'
services:
  app:
    build: ./
    command: sh -c "flask run --host=0.0.0.0 --port=5000"
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server.py
    working_dir: /code/
# uncomment to develop in local folder and run in docker container
# Note: npm is not on final docker image, so you would need to install
# locally and run "npm run watch"
#    volumes:
#      - ./:/code/:cached