version: '3'
services:
  app:
    build: ./
    command: sh -c "npm run devserver"
    ports:
      - '5000:5000'
    environment:
      - FLASK_ENV=develpment
    working_dir: /code/
    volumes:
      - ./:/code/:cached